import '@styles/global.css';

export const metadata = {
    title: 'GitHub Repo Search',
    description: 'Generated by Next.js and GitHub API',
  }

const layout = () => {
  return (
    <div>layout</div>
  )
}

export default layout