import '@styles/global.css';

export const metadata = {
    title: 'GitHub Repo Search',
    description: 'Generated by Next.js and GitHub API',
  }

const Rootlayout = () => {
  return (
    <html lang="en">
        <body>
            <div className="main">
                <div className="gradient" />
            </div>

            <main className="app">
                {children}
            </main>
        </body>
    </html>
  )
}

export default Rootlayout