import '@styles/global.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }

const layout = () => {
  return (
    <div>layout</div>
  )
}

export default layout